# Generated by Django 2.1.7 on 2019-09-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblab', '0002_auto_20190813_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LAS', 'Laser on'), ('LAE', 'Laser off'), ('LOI', 'Logged in'), ('LOO', 'Logged out')], default='LOI', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblab.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblab.Person')),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblab.RFIDTag')),
            ],
        ),
    ]
