# Generated by Django 2.1.7 on 2019-09-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblab', '0003_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
