# Generated by Django 2.1.7 on 2020-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblab', '0008_auto_20200221_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='laser_usage_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
