# Generated by Django 2.1.7 on 2020-02-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblab', '0009_log_laser_usage_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='usage_time',
            new_name='logged_time',
        ),
    ]
