# Generated by Django 2.1.7 on 2020-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblab', '0014_auto_20200221_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdaily',
            name='event',
        ),
        migrations.AddField(
            model_name='logdaily',
            name='laser_usage_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logdaily',
            name='usage_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventDaily',
        ),
    ]
